[package]
name = "gpu"
version = "0.1.0"
authors = ["Nicolas Silva <nical@fastmail.com>"]
edition = "2018"
workspace = "../.."

[dependencies]
wgpu = "0.6"
winit = "0.20.0-alpha4"
glue = { path = "../glue" }
cache = { path = "../cache" }
pipe = { path = "../pipe" }
