[package]
name = "playground"
version = "0.1.0"
authors = ["Nicolas Silva <nical@fastmail.com>"]
workspace = "../.."
edition = "2018"

[dependencies]
glue = { path = "../glue" }
gpu = { path = "../gpu" }
pipe = { path = "../pipe" }
cache = { path = "../cache" }
lyon = { path = "../../", features = ["extra"] }

wgpu = "0.6"
winit = "0.20.0-alpha4"
futures = "0.3.5"
